#!/usr/bin/env python3
# This file is a part of marzer/soagen and is subject to the the terms of the MIT license.
# Copyright (c) Mark Gillard <mark.gillard@outlook.com.au>
# See https://github.com/marzer/soagen/blob/master/LICENSE for the full license text.
# SPDX-License-Identifier: MIT

"""
Constants for various key paths.
"""

import tempfile
from pathlib import Path

PACKAGE = Path(Path(__file__).resolve().parent)
"""The root directory of the package installation."""

DATA = Path(PACKAGE, r'data')
"""The root directory of all package data."""

HPP_TEMPLATES = Path(DATA, r'hpp_templates')
"""The directory containing soagen's .hpp template files"""

HPP = Path(DATA, r'hpp')
"""The directory containing soagen's (non-autogenerated) hpp files."""

REPOSITORY = Path(PACKAGE, r'..')
"""The root directory of the repository."""

TESTS = Path(REPOSITORY, r'tests')
"""The root directory of the repository's tests."""

TEMP = Path(tempfile.gettempdir(), r'soagen')
"""A global temp directory shared by all instances of soagen."""

MAKE_SINGLE = Path(REPOSITORY, r'..', r'muu', r'tools', r'make_single.py')
