#!/usr/bin/env python3
# This file is a part of marzer/soagen and is subject to the terms of the MIT license.
# Copyright (c) Mark Gillard <mark.gillard@outlook.com.au>
# See https://github.com/marzer/soagen/blob/master/LICENSE for the full license text.
# SPDX-License-Identifier: MIT

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING, cast
from xml.sax.saxutils import escape

from . import utils
from .column import *
from .configurable import Configurable
from .metavars import *
from .version import *
from .writer import *

if TYPE_CHECKING:
    from .struct import Struct

_GLOBAL_SCOPE_TYPES = frozenset(
    (
        'void', 'bool', 'char', 'wchar_t', 'char8_t', 'char16_t', 'char32_t',
        'short', 'int', 'long', 'float', 'double', 'signed', 'unsigned',
        'size_t', 'ptrdiff_t', 'intptr_t', 'uintptr_t', 'intmax_t', 'uintmax_t', 'nullptr_t', 'max_align_t',
        'int8_t', 'int16_t', 'int32_t', 'int64_t', 'uint8_t', 'uint16_t', 'uint32_t', 'uint64_t',
    )
)  # fmt: skip


def _natvis_cast_type(type_str: str, namespace: str) -> str:
    t = type_str.strip()
    if not namespace or t in _GLOBAL_SCOPE_TYPES or not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', t):
        return t
    return f'{namespace}::{t}'


class NatvisFile(Configurable):
    path: Path
    structs: tuple[Struct, ...]
    meta: MetaVars

    def __init__(self, config, structs):
        super().__init__(config)
        self.path = self.config.out_dir / rf'{self.config.path.stem}.natvis'
        self.structs = cast('tuple[Struct, ...]', tuple(utils.coerce_collection(structs)))

        self.meta = MetaVars()
        for prefix in (r'file_', r'file::'):
            self.meta.push(rf'{prefix}name', self.path.name)
            self.meta.push(rf'{prefix}path', str(self.path))

    def write(self, o: Writer):
        with MetaScope(self):
            o(
                rf'''
            <?xml version="1.0" encoding="utf-8"?>
            <!--
            // This file was generated by soagen v{VERSION_STRING} - do not modify it directly
            // https://marzer.github.io/soagen
            -->
            <AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
            '''
            )

            with Indent(o):
                for struct in self.structs:
                    with MetaScope(struct):
                        o(
                            rf'''
                        <!--{"=" * (120 - o.indent_width - 4)}
                        {struct.name}
                        {"=" * (120 - o.indent_width - 3)}-->'''
                        )
                        with Indent(o, pre=f'\n\n<Type Name="{escape(struct.qualified_type)}">', post='</Type>'):
                            o(
                                r'''
                            <Intrinsic Name="size" Expression="table_.count_" />
                            <Intrinsic Name="size_bytes" Expression="table_.alloc_.size" />
                            <Intrinsic Name="capacity" Expression="table_.capacity_.first_" />
                            '''
                            )
                            for col in struct.columns:
                                o(
                                    rf'''
                                <Intrinsic
                                    Name="get_{col.index}"
                                    Expression="reinterpret_cast&lt;{escape(_natvis_cast_type(col.type, self.config.namespace))}*&gt;(table_.alloc_.columns[{col.index}])"
                                />
                                '''
                                )
                            o(r'<DisplayString>{{ size={size()} }}</DisplayString>')
                            with Indent(o, pre='<Expand>', post='</Expand>\n'):
                                o(
                                    r'''
                                <Item Name="[size]">size()</Item>
                                <Item Name="[capacity]">capacity()</Item>
                                <Item Name="[allocation_size]">size_bytes()</Item>
                                '''
                                )
                                for col in struct.columns:
                                    get = rf'get_{col.index}()'
                                    o(
                                        rf'''
                                    <Synthetic Name="{col.name}">
                                        <DisplayString Condition="size() &gt; 3u">{{{{ {{*({get})}}, {{*({get} + 1)}}, {{*({get} + 2)}}, ... }}}}</DisplayString>
                                        <DisplayString Condition="size() == 3u">{{{{ {{*({get})}}, {{*({get} + 1)}}, {{*({get} + 2)}} }}}}</DisplayString>
                                        <DisplayString Condition="size() == 2u">{{{{ {{*({get})}}, {{*({get} + 1)}} }}}}</DisplayString>
                                        <DisplayString Condition="size() == 1u">{{{{ {{*({get})}} }}}}</DisplayString>
                                        <DisplayString Condition="size() == 0u"></DisplayString>
                                        <Expand>
                                            <ArrayItems>
                                                <Size>size()</Size>
                                                <ValuePointer>{get}</ValuePointer>
                                            </ArrayItems>
                                        </Expand>
                                    </Synthetic>
                                    '''
                                    )

                        row_types = [
                            rf'soagen::row<{struct.qualified_type}, {struct.column_indices}>',
                            rf'soagen::row<{struct.qualified_type}&, {struct.column_indices}>',
                            rf'soagen::row<{struct.qualified_type}&&, {struct.column_indices}>',
                            rf'soagen::row<const {struct.qualified_type}, {struct.column_indices}>',
                            rf'soagen::row<const {struct.qualified_type}&, {struct.column_indices}>',
                            rf'soagen::row<const {struct.qualified_type}&&, {struct.column_indices}>',
                        ]
                        with Indent(o, pre=f'\n\n<Type Name="{escape(row_types[0])}">', post='</Type>'):
                            for i in range(1, len(row_types)):
                                o(rf'<AlternativeType Name="{escape(row_types[i])}" />')

                            s = r''
                            if len(struct.columns) > 1:
                                s += r'{{ '
                            s += r'{'
                            s += r'}, {'.join(col.name for col in struct.columns[:8])
                            s += r'}'
                            if len(struct.columns) > 8:
                                s += r', ...'
                            if len(struct.columns) > 1:
                                s += r' }}'
                            o(rf'<DisplayString>{s}</DisplayString>')
                            with Indent(o, pre='<Expand>', post='</Expand>\n'):
                                for col in struct.columns:
                                    o(rf'<Item Name="{col.name}">{col.name}</Item>')

            o(r'</AutoVisualizer>')


__all__ = [r'NatvisFile']
